# Generated by Django 4.1.6 on 2023-02-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_rec', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpotifyProfile',
        ),
    ]
